root: true

parser: 'babel-eslint'

plugins:
  - flowtype
  - standard

extends:
  - eslint:recommended
  - standard
  - plugin:flowtype/recommended

env:
  node: true

parserOptions:
  ecmaVersion: 7

# List of available rules - ESLint http://eslint.org/docs/rules/
rules:
  no-console: "off"
